<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <ApplicationIcon>..\AgentSignaler.Configurator\AgentSignaler.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AgentSignaler.Remote\AgentSignaler.Remote.csproj" />
  </ItemGroup>
</Project>
